### PR TITLE
Add Section and Vlan import feature

### PR DESCRIPTION
**Pull request by peterbaumert**
I'm neither a go expert nor an terraform expert. I simply copied and edited from other files so please check :)

### CODE REVIEW

**Comment by pavel-z1** [comment]
Hi @peterbaumert 
Thanks for reporting the problem with importing VLAN and Section resources

Currently this PR has errors during build:
```
plugin/providers/phpipam/data_source_phpipam_section.go:49:23: undefined: strconv
plugin/providers/phpipam/data_source_phpipam_section.go:53:7: invalid operation: cannot index out (variable of type sections.Section)
plugin/providers/phpipam/data_source_phpipam_vlan.go:54:20: undefined: strconv
plugin/providers/phpipam/data_source_phpipam_vlan.go:58:7: invalid operation: cannot index out (variable of type vlans.VLAN)
```

To fix errors make this changes:
```
index 3b4add74..23685932 100644
--- a/plugin/providers/phpipam/data_source_phpipam_vlan.go
+++ b/plugin/providers/phpipam/data_source_phpipam_vlan.go
@@ -2,6 +2,7 @@ package phpipam

 import (
        "errors"
+       "strconv"

        "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
        "github.com/pavel-z1/phpipam-sdk-go/controllers/vlans"
@@ -55,7 +56,7 @@ func dataSourcePHPIPAMVLANRead(d *schema.ResourceData, meta interface{}) error {
                        if err != nil {
                                return err
                        }
-                       out[0], err = c.GetVLANByID(vlan_id)
+                       out, err = c.GetVLANByID(vlan_id)
                        if err != nil {
                                return err
                        }
```

```
index a2f8fb0d..5c9674dc 100644
--- a/plugin/providers/phpipam/data_source_phpipam_section.go
+++ b/plugin/providers/phpipam/data_source_phpipam_section.go
@@ -4,6 +4,7 @@ import (
        "errors"
        "log"
        "strings"
+       "strconv"

        "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
        "github.com/pavel-z1/phpipam-sdk-go/controllers/sections"
@@ -50,7 +51,7 @@ func dataSourcePHPIPAMSectionRead(d *schema.ResourceData, meta interface{}) erro
                        if err != nil {
                                return err
                        }
-                       out[0], err = c.GetSectionByID(section_id)
+                       out, err = c.GetSectionByID(section_id)
                        if err != nil {
                                return err
                        }
```

Also, please rebase commits in this PR to the single commit.

**Comment by peterbaumert** [comment]
@pavel-z1 added your changed and did a single commit.

**Comment by peterbaumert** [comment]
would you mind having a look at this @pavel-z1 ?

**Comment by pavel-z1** [comment]
Hi @peterbaumert 
I am waiting for previous PR (https://github.com/lord-kyron/terraform-provider-phpipam/pull/86) first to accept this

**Review by nullck — APPROVED** [review]
LGTM

**Review by pavel-z1 — APPROVED** [review]

**Comment by peterbaumert** [comment]
Ty @pavel-z1 could you also generate a new release?

**Comment by lord-kyron** [comment]
@peterbaumert I will generate a new release when the last 3 pull requests currently pending get approved and merged.

**Comment by peterbaumert** [comment]
Okay sounds good. Thanks for the info!

**Comment by peterbaumert** [comment]
@lord-kyron could you generate the release? :)

**Comment by lord-kyron** [comment]
@peterbaumert new release was generated. Enjoy!

**Pull request merged**
