### PR TITLE
Added l2domains controller. Fixed various bugs in another controllers

### PR DESCRIPTION
**Pull request by pavel-z1**
- added posibility to create Vlan with the same number id different l2_domains
- added posibility to create Subnet with the same CIDR in different Sections
- fixed read subnet data resource with section_id, subnet_address and subnet_mask parameters
- created terraform resource and data packages for l2domains controller
- fixed modules dependencies that will allow to run `make testacc` command
- fixed custom field read for data sources (subnet, address, vlan)
- fixed clean up custom field during resource update
- refactored Unit tests

### CODE REVIEW

**Comment by pavel-z1** [comment]
Hi @lord-kyron 
This PR contains a large number of changes in the overlapping parts of the code. Therefore, to speed up the work, they were merged into one commit.
First major implementation - added ability to manage l2fomains
The second significant change is the refactoring of Unit tests and bringing them back to life.

There are also a number of smaller changes that affect bugs and fixes discovered after the restoration of Unit tests

[This issue](https://github.com/lord-kyron/terraform-provider-phpipam/issues/66) fixed here too.

**Comment by pavel-z1** [comment]
Fix for [issue](https://github.com/lord-kyron/terraform-provider-phpipam/issues/67) added.

**Comment by MatthieuuC** [comment]
I've just tested it's not working, let me fix this before merge please :)

**Comment by MatthieuuC** [comment]
It's fixed in https://github.com/pavel-z1/phpipam-sdk-go/pull/15

**Comment by pavel-z1** [comment]
Hi @MatthieuuC 
I propose to move this issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/67 and discussion of its solution to the SDK project as reported issue not related to this project and PR.

**Comment by pavel-z1** [comment]
@lord-kyron , I've recreated SDK release with tag v0.1.7 with included updated related to GET request
No PR update needed here.
We can merge PR

**Review by lord-kyron — APPROVED** [review]

**Pull request merged**
