### PR TITLE
implement fork

### PR DESCRIPTION
**Pull request by cristicalin**

### CODE REVIEW

**Comment by pavel-z1** [comment]
Hi @lord-kyron 
We have new maintainer for phpipam plugin?

A long of time we supported SDK here https://github.com/pavel-z1/phpipam-sdk-go
But I see that suddenly link to sdk was changed to the forked repo with minor change without discussion.

May I have your opinion on this change?

**Comment by lord-kyron** [comment]
Ah @pavel-z1 it seems I approved it without actually seeing this particular change. It was by my mistake. I will revert the change.
Sorry!

**Comment by lord-kyron** [comment]
@pavel-z1 
I've reviewed the merged pull requests, and it seems to me that this was not merged.
Our current and latest versions are still based on your sdk repository. This pull request was closed by the requestor itself.
Or I am missing something?

**Comment by cristicalin** [comment]
my bad on this one, i meant to open it on my own fork of this repo but got fulled by GitHub UI that's why I closed it, the intention was to be able to test the build in CI with the proxy fix I submitted to @pavel-z1 's sdk

**Comment by lord-kyron** [comment]
The sdk provider repo was already updated with anoterh pull request

**Pull request closed without merging**
